### ISSUE TITLE
All hashes in one file

### ISSUE THREAD

**Issue by Richienb** [bytesoverbombs/VirusShare-Search#3]
All the hashes should be in a single file for simplicity. There is a project called [VirusShare Hashes](https://www.richie-bendall.ml/virusshare-hashes/) which does this. It provides a comprehensive and automatically updating list of hashes from VirusShare so you could just download from there.

**Comment by Richienb** [comment]
@bytesoverbombs Any update on this?

**Comment by bytesoverbombs** [comment]
No update on your suggestion. You're welcome to submit a pull request
